import 'package:flutter/material.dart';

class Common {
  Common._();

  static List<String> kinh = ['Đi bộ',
    'Chạy',
    'Nhảy',
    'Ngồi',
    'Đứng',
    'Ngủ',
    'Ăn',
    'Uống',
    'Đọc',
    'Viết',
    'Nói',
    'Nghe',
    'Nhìn',
    'Thấy',
    'Nói chuyện',
    'Hét lên',
    'Thì thầm',
    'Hỏi',
    'Trả lời',
    'Cười lớn',
    'Khóc',
    'Giữ',
    'Nắm lấy',
    'Đẩy',
    'Kéo',
    'Ném',
    'Bắt',
    'Vỗ tay',
    'Cười mỉm',
    'Ngáp',
    'Duỗi người',
    'Vẫy tay',
    'Ôm',
    'Hôn',
    'Gật đầu',
    'Lắc đầu',
    'Vẽ tranh',
    'Nhảy múa',
    'Hát',
    'Chơi',
    'Xây dựng',
    'Sửa chữa',
    'Nấu ăn',
    'Núi',
    'Sông',
    'Hồ',
    'Biển',
    'Rừng',
    'Bãi biển',
    'Sa mạc',
    'Đồi',
    'Thung lũng',
    'Thác nước',
    'Đồng bằng',
    'Hang động',
    'Vách đá',
    'Đảo',
    'Cây',
    'Hoa',
    'Cỏ',
    'Bầu trời',
    'Mây',
    'Mặt trời',
    'Mặt trăng',
    'Ngôi sao',
    'Trái đất',
    'Cánh đồng',
    'Con đường',
    'Lối đi',
    'Cầu',
    'Thị trấn',
    'Làng',
    'Bạn',
    'Tên',
    'Bạn',
    'Bạn',
    'Mình',
    'Cảm ơn',
    'Không',
    'Xin',
    'Tôi',
    'Làm',
    'Bạn',
    'Tôi',
    'Hẹn',
    'Chào',
    'Chúc',
    'Bảo',
    'Mấy',
    'Cái',
    'Anh',
    'Mình',
    'Trường học',
    'Lớp học',
    'Giáo viên',
    'Học sinh',
    'Bàn học',
    'Ghế',
    'Bảng đen',
    'Bảng trắng',
    'Bút',
    'Bút chì',
    'Cục tẩy',
    'Sách',
    'Vở',
    'Môn học',
    'Bài học',
    'Bài tập về nhà',
    'Kỳ thi',
    'Kiểm tra',
    'Điểm',
    'Cặp sách',
    'Đồng phục',
    'Hiệu trưởng',
    'Hiệu phó',
    'Bạn học',
    'Thư viện',
    'Phòng tập thể dục',
    'Máy tính',
    'Máy in',
    'Bản đồ',
    'Phấn',
    'Thước kẻ',
    'Lịch',
    'Đèn bàn',
    'Mỹ thuật',
    'Khoa học',
    'Lịch sử',
    'Toán học',
    'Văn học',
    'Địa lý',
    'Ngữ văn',
    'Giáo dục thể chất',
    'Sức khoẻ',
    'Bác sĩ',
    'Y tá',
    'Bệnh viện',
    'Phòng khám',
    'Hiệu thuốc',
    'Thuốc',
    'Điều trị',
    'Đơn thuốc',
    'Căn bệnh',
    'Bệnh',
    'Đau',
    'Sốt',
    'Cảm lạnh',
    'Ho',
    'Đau đầu',
    'Đau bụng',
    'Viêm họng',
    'Chấn thương',
    'Phẫu thuật',
    'Ca mổ',
    'Hồi phục',
    'Tiêm phòng',
    'Kiểm tra sức khoẻ',
    'Huyết áp',
    'Xét nghiệm máu',
    'Chụp X-quang',
    'Xe cấp cứu',
    'Sơ cứu',
    'Bảo hiểm sức khoẻ',
    'Tập thể dục',
    'Chế độ ăn uống',
    'Dinh dưỡng',
    'Thể hình',
    'Giảm cân',
    'Giấc ngủ',
    'Sức khoẻ tâm thần',
    'Căng thẳng',
    'Lo âu',
    'Trầm cảm',
    'Thư giãn',
    'Vệ sinh',
    'Khoẻ mạnh',
    'Ốm',
    'Yêu cầu',
    'Hỏi',
    'Đòi hỏi',
    'Mong muốn',
    'Hy vọng',
    'Khao khát',
    'Làm ơn',
    'Bạn có thể',
    'Bạn có thể làm ơn',
    'Bạn có thể giúp tôi',
    'Cho phép tôi',
    'Tôi muốn',
    'Tôi cần',
    'Tôi muốn nói',
    'Bạn có phiền không',
    'Có thể không',
    'Xin phép',
    'Tôi cầu xin',
    'Tôi hy vọng',
    'Tôi mong',
    'Bạn làm ơn giúp tôi',
    'Tôi rất cảm ơn',
    'Có thể giúp tôi không',
    'Xin vui lòng',
    'Giúp tôi nhé'];
  static List<String> dao = ['Mình dạo',
    'Thỉu',
    'thiu',
    'duôi',
    'xâu',
    'puổi',
    'nhẹn',
    'hốp',
    'tổ xâu',
    'khia xâu',
    'phu',
    'móng',
    'mạng',
    'puộn nhe',
    'cong vạ',
    'hệu',
    'cong bạ phải',
    'nại muồi',
    'muồi cong',
    'chắc',
    'nhiếp',
    "nan",
    'nan lậu',
    'nhi phông',
    'peng',
    'phếnh',
    'sang so',
    'vai pua',
    'chác',
    'Ngáp',
    'Pút luội',
    'Vạy pua',
    'hóp',
    'yên hăm',
    'khẩy ngon',
    'hạ ngon',
    'muồi vẽ',
    'tèo',
    'páo dung',
    'mình dạo',
    'xậu páo',
    'sọ',
    'sâu hảng',
    'Kềm',
    'Vồm tông',
    'Vò meng',
    'Biển',
    'Kềm',
    'Bãi biển',
    'Sa mạc',
    'Kềm',
    'Thung lũng',
    'Vòm thác',
    'Đào pèng',
    'Đào lạng',
    'Vènh pẹ',
    'Đảo',
    'Giảng',
    'Pèng',
    'Mia',
    'Pò hoi',
    'Lùng beng',
    'Pò hoi',
    'Hả',
    'Suất sao',
    'Đia đao',
    'Há lang',
    'Chao',
    'Chào mình',
    'Chiều',
    'Tồm lang',
    'Mua dao',
    'Tồng nìn',
    'Búa',
    'Tồng nìn',
    'Tồng nìn',
    'Muồi',
    'Cảm ơn',
    'Mí mài',
    'Thô',
    'Dia',
    'Dâu công',
    'Tồng nìn',
    'Dia',
    'Dia puông',
    'Chào',
    'Chúc muồi',
    'Día púa muồi',
    'Nóng mấy',
    'Nong',
    'Có',
    'Dia',
    '    Cong nong trường ',
    'Nong lớp',
    'Giaos viên',
    'Chuôi',
    'Bàn học',
    'Hẩy tôn',
    'Thầy bảng',
    'Bảng phia',
    'Bút',
    'Bút chì',
    'Cục tẩy',
    'sâu',
    'sâu phia',
    'Môn',
    'Bài sâu',
    'Duổn pao la',
    'Ghét muồi',
    'Mạng muồi',
    'Điểm',
    'Bụa sâu',
    'Đồng phục',
    'Hiệu trưởng',
    'Hiệu phó',
    'Tùng nìn',
    'Thư viện',
    'Phòng tập thể dục',
    'Máy tính',
    'Máy in',
    'Bản đồ',
    'Phấn',
    'Thước kẻ',
    'Lịch',
    'Âu tang',
    'Mỹ thuật',
    'Khoa học',
    'Lịch sử',
    'Toán học',
    'Văn học',
    'Địa lý',
    'Ngữ văn',
    ' Giáodục thể chất',
    'Mảy xa ne',
    'Bác sĩ',
    'Y tá',
    'Bệnh viện',
    'Phòng khám',
    'Hiệu thuốc',
    'Thuốc',
    'Mình xọ bệnh',
    'đia',
    'Bệnh nhè',
    'Pus bệnh',
    'Mun',
    'Đang pu chóa',
    'Đang pú chóa',
    'Đang pút hốp',
    'Gong mun',
    'Kề xi mun',
    'Chang mun',
    'Dia chang mun',
    'Đang mì phải',
    'Đang phái',
    'Diêm lống lá',
    'Mình tiêm',
    'Nhi khám',
    'Huyết áp',
    'Do diem',
    'Chụp X-quang',
    'Cho xe minh kham',
    'Sơ cứu',
    'Bảohiểm sức khoẻ',
    'Tập thể dục',
    'Đang nhẹn',
    'Nhen xang',
    'Thể hình',
    'Dia giảm',
    'Dia puổi tớ tẩy á',
    'Pu tin',
    'Căng thẳng',
    'Dào',
    'Pha chẹ',
    'Má hai dào',
    'Puốt đao',
    'Dia đang mài sạ',
    'Đang di tang pút pẻng',
    'Mình thỉnh công',
    'Nại muồi',
    'Toi muồi',
    'Đang lác',
    'Hy vọng',
    'Khao khát',
    'Làm ơn',
    'Bạn có thể',
    'Bạn có thể làm ơn',
    'Mình thỉnh dia tu dẹ',
    'Muồi pun dia he',
    'Muồi pun dia',
    'Dia muồn puôi duổi',
    'Dia nại muồi',
    'Muồi tua củng nhe',
    'Tu nhẹ',
    'Tho muôi',
    'tho',
    'diếm oi',
    'dia ỏi',
    'muồi thỉnh nhi',
    'dia pong vai',
    'muồi thinh dia',
    'dia hai dạo',
    'thỉnh dia'];
  static List<String> anh = ['Walk',
    'Run',
    'Jump',
    'Sit',
    'Stand',
    'Sleep',
    'Eat',
    'Drink',
    'Read',
    'Write',
    'Speak',
    'Listen',
    'Look',
    'See',
    'Talk',
    'Shout',
    'Whisper',
    'Ask',
    'Answer',
    'Laugh',
    'Cry',
    'Hold',
    'Grab',
    'Push',
    'Pull',
    'Throw',
    'Catch',
    'Clap',
    'Smile',
    'Yawn',
    'Stretch',
    'Wave',
    'Hug',
    'Kiss',
    'Nod',
    'Shake',
    'Paint',
    'Dance',
    'Sing',
    'Play',
    'Build',
    'Fix',
    'Cook',
    'Mountain',
    'River',
    'Lake',
    'Ocean',
    'Forest',
    'Beach',
    'Desert',
    'Hill',
    'Valley',
    'Waterfall',
    'Plain',
    'Cave',
    'Cliff',
    'Island',
    'Tree',
    'Flower',
    'Grass',
    'Sky',
    'Cloud',
    'Sun',
    'Moon',
    'Star',
    'Earth',
    'Field',
    'Road',
    'Path',
    'Bridge',
    'Town',
    'Village',
    'How',
    'What’s',
    'Where',
    'How',
    'I’m',
    'Thank',
    'You’re',
    'Excuse',
    'I’m',
    'Please.',
    'Can',
    'I',
    'See',
    'Good',
    'Have',
    'Take',
    'What’s',
    'How',
    'I',
    'I’m',
    'School',
    'Classroom',
    'Teacher',
    'Student',
    'Desk',
    'Chair',
    'Blackboard',
    'Whiteboard',
    'Pen',
    'Pencil',
    'Eraser',
    'Book',
    'Notebook',
    'Subject',
    'Lesson',
    'Homework',
    'Exam',
    'Test',
    'Grade',
    'Schoolbag',
    'Uniform',
    'Principal',
    'Headmaster',
    'Schoolmate',
    'Library',
    'Gym',
    'Computer',
    'Printer',
    'Map',
    'Chalk',
    'Ruler',
    'Calendar',
    'Desk lamp',
    'Art',
    'Science',
    'History',
    'Mathematics',
    'Literature',
    'Geography',
    'Language',
    'Physical education',
    'Health',
    'Doctor',
    'Nurse',
    'Hospital',
    'Clinic',
    'Pharmacy',
    'Medicine',
    'Treatment',
    'Prescription',
    'Illness',
    'Disease',
    'Pain',
    'Fever',
    'Cold',
    'Cough',
    'Headache',
    'Stomach ache',
    'Sore throat',
    'Injury',
    'Surgery',
    'Operation',
    'Recovery',
    'Vaccination',
    'Check-up',
    'Blood pressure',
    'Blood test',
    'X-ray',
    'Ambulance',
    'First aid',
    'Health insurance',
    'Exercise',
    'Diet',
    'Nutrition',
    'Fitness',
    'Weight loss',
    'Sleep',
    'Mental health',
    'Stress',
    'Anxiety',
    'Depression',
    'Relaxation',
    'Hygiene',
    'Healthy',
    'Sick',
    'Request',
    'Ask',
    'Demand',
    'Wish',
    'Hope',
    'Desire',
    'Please',
    'Can you',
    'Could you',
    'Would you',
    'Let me',
    'I want',
    'I need',
    'I would like',
    'Would you mind',
    'Is it possible',
    'Allow me',
    'I beg you',
    'I hope',
    'I wish',
    'Could you please',
    'Please help me',
    'I would appreciate',
    'May I',
    'I need your help'];
  static List<String> pathen = ['Nhi chả cu nhi',
    'Tờ xì dớ',
    'Tơ xi nhọ',
    'Tơ xi dú',
    'Tơ xi sợ nha',
    'Tơ xi pớ',
    'Tơ xi nó i',
    'Ó o',
    'Tờ xi tơ xí',
    'Tơ xi xạ xí',
    'Tơ xi nạ cô củng',
    'Tơ xi má',
    'Tơ xi do múng',
    'Hâu pằm pú ne',
    'Tơ xi co củng',
    'Tơ xi cơ múng',
    'Tơ xi ý dớ cọ',
    'Tơ xi ni mung',
    'Tơ xi di da mung',
    'Tơ xi da mung cha',
    'Tơ xi gá le',
    'Tơ xi khá múng hơ',
    'Tơ xi dá múng khá ta phư',
    ' Tơ xin đí mủng',
    'Tơ xi qué mủng ne',
    'Tơ xi khá mụng',
    'Tơ xi chọ',
    'Tơ xi vô tay',
    'Tơ xi tá mung nẹ',
    'Tơ xi nghè',
    'Tơ xi pơ khé',
    'Tơ xi chào mung ne',
    'Tơ xi tau mung tạo dợ',
    'Tơ xi dao mung ta dự',
    'Tơ xi ngó ngó',
    'Tơ xi quy chú ngu',
    'Tơ xi vẽ tranh',
    'Tơ xi múa văn nghệ',
    'Tơ xi I xé',
    'Tơ xi nhính gự',
    'Tơ xi í pơ',
    'Tơ xi pé',
    'Tơ xi í nọ',
    'Tơ duy',
    'Sông',
    'Hồ',
    'Biển',
    'Co dọ',
    'Bãi biển',
    'Sa mạc',
    'Tơ duy',
    'Thung lũng',
    'Tơ o',
    'A so pỉ',
    'Á khụng du',
    'Pí dụ',
    'Đảo',
    'Tợ pạ',
    'Booc',
    'Sụ',
    'Au ngo',
    'Bú hụ',
    'An hi',
    'An lác',
    'Bàu xô',
    'Ca li',
    'Ni thung nhi',
    'Tơ cụ',
    'Tơ cụ nhi',
    'Tơ chớ',
    'Ta chợ nhi',
    'Ni khu me',
    'Mung nhinh gư',
    'Tơ xi quá chi',
    'Mung',
    'Mùng',
    'Vò',
    'Dạ ơn',
    'Mí',
    'Tơ xi dá múng qợ',
    'Láy i',
    'Í cúng',
    'Mung',
    'Lay i',
    'Pơ xi tình',
    'Í nha tì',
    'Mủ nhung áp pủ la',
    'Ti bò hụ',
    'Mủng mi ge cho',
    'Gá da',
    'Au ú',
    'Mùng',
    'A pịa tơ xí',
    'Tơ xi tơ xí',
    'Giaos viên',
    'Ta ka',
    'Ke pa tơ xí',
    'A thú',
    'A bảng',
    'Pau co',
    'Tơ pí',
    'Pu chi',
    'Cục tẩy',
    'Pin đọ',
    'Pi đo xạ',
    'Môn',
    'Tơ xi ne',
    'Tơ xi tơ xi',
    ' tơ xi thị',
    'Cha mủng',
    'Mung điểm',
    'A thứ',
    'Kế ợ',
    'Hiểu trưởng',
    'Hiệu phó',
    'Dao mủng tớ xí',
    'A pìa đọ',
    'A pịa tơ ni pia tơ thể dục',
    'Máy tính',
    'Máy in',
    'Bản đồ',
    'Bỉ sa xí',
    'Tơ pịa kẻ',
    'Lịch',
    'Á tính',
    'Mỹ thuật',
    'Khoa học',
    'Lịch sử',
    'Toán học',
    'Văn học',
    'Địa lý',
    'Ngữ văn',
    'Giáo dục thể chất',
    'Mi xá lẹ',
    'Bác sĩ',
    'Y tá',
    'Bệnh viện',
    'Phòng khám',
    'Hiệu thuốc',
    'Thuốc',
    'Nhi pay mạ',
    'Hó da',
    'Minh ma',
    'Ma',
    'Ma quá',
    'Tơ xí í nhú',
    'Đa í nhúng',
    'Tơ xi khó',
    'Tơ xi ma dú pị',
    'Tơ xi ma hụng',
    'Tơ xi ma chú ngụng',
    'Tơ xi ma',
    'Tờ xi nhí phá',
    'Tơ xi phái',
    'Tơ xí ché',
    'Nhi túng',
    'Tơ xi nhi khám',
    'Huyết áp',
    'Nhi cứ chợ',
    'Chụp X-quang',
    'Tơ xe cừ mứ nhi',
    'Tơ xi nhi túng',
    'Bảo hiểm sức khoẻ',
    'Tập thể dục',
    'Tơ xi no hơ',
    'No hơ cho',
    'Thể hình',
    'Ha cung',
    'Po tơ chi nẹ',
    'Pha chẹ',
    'Căng thẳng',
    'Dợ lắm',
    'Pu tin',
    'Tơ xi nhu',
    'Tơ xi cu pịa',
    'Ba may tơ xin chẻ',
    'Tơ xi ma',
    'Pó mung tưa',
    'Nỉ mủng',
    'Tơ xi to',
    'Tơ xi vớ',
    'Hy vọng',
    'Khao khát',
    'Làm ơn',
    'Bạn có thể',
    'Bạn có thể làm ơn',
    'Pó tư hò lẹ',
    'Mờ cứ họ lẹ',
    'Vò vỡ dạ',
    'Vò vơ mủ',
    'Vò dả nỉ mù',
    'Mù chứ lạ',
    'Di tứ lạ',
    'Co phai mua',
    'Tơ xi da múng gơ',
    'Tơ xi vọng vơ',
    'Tơ xi vớ',
    'Po vòng tứ lạng',
    'Tơ xe mung',
    'Po mầy tứ lạ',
    'Mươi xí',
    'Pó mò'];

  static void showLoadingDialog(BuildContext context, String text) {
    showDialog(
      context: context,
      barrierDismissible: false, // Prevent user from dismissing the dialog
      builder: (BuildContext context) {
        return Dialog(
          child: Padding(
            padding: const EdgeInsets.all(16.0),
            child: Row(
              mainAxisSize: MainAxisSize.min,
              children: [
                const CircularProgressIndicator(
                  color: Colors.orange,
                ),
                // Display a circular progress indicator
                const SizedBox(width: 16.0),
                Text(text),
                // Display a text message
              ],
            ),
          ),
        );
      },
    );
  }

  static void hideLoadingDialog(BuildContext context) {
    Navigator.of(context).pop(); // Close the dialog
  }

  static void showAlertDialog(
      BuildContext context, String title, String content) {
    showDialog(
      context: context,
      builder: (BuildContext context) {
        return AlertDialog(
          title: Text(title),
          content: Text(content),
          actions: <Widget>[
            TextButton(
              child: const Text("OK"),
              onPressed: () {
                Navigator.of(context).pop(); // Close the dialog
              },
            ),
          ],
        );
      },
    );
  }
}
