import 'package:flutter/material.dart';

class Common {
  Common._();

  static List<String> kinh = [
    'bạn có nói được tiếng anh không',
    'không tôi không biết nhưng tôi dùng thiết bị hỗ trợ',
    'bạn tên gì',
    'tôi tên nam',
    'bạn từ đâu đến',
    'tôi từ huế',
    'bạn làm gì',
    'tôi làm giáo viên',
    'bạn có thích cà phê không',
    'có tôi thích',
    'bạn ăn sáng chưa',
    'chưa tôi chưa',
    'bạn có cần giúp không',
    'có giúp tôi',
    'bạn có rảnh không',
    'có tôi rảnh',
    'bạn có đi xem phim không',
    'có tôi đi',
    'bạn có biết không',
    'có tôi biết',
    'bạn thích đọc sách gì',
    'tôi thích tiểu thuyết',
    'hôm nay trời đẹp không',
    'có trời đẹp',
    'bạn đã ăn trưa chưa',
    'chưa tôi chưa',
    'bạn có nghe nhạc không',
    'có tôi nghe',
    'bạn có đi du lịch không',
    'có tôi đi',
    'bạn thích món ăn nào',
    'tôi thích phở',
    'bạn có cần uống nước không',
    'có tôi cần',
    'bạn đã xem chương trình chưa',
    'chưa tôi chưa',
    'bạn có biết địa chỉ không',
    'có tôi biết',
    'bạn có thể giúp tôi không',
    'có tôi giúp',
    'bạn có thích thể thao không',
    'có tôi thích',
    'bạn có muốn gặp tôi không',
    'có tôi muốn',
    'bạn có xem tin tức không',
    'có tôi xem',
    'bạn có đi làm sớm không',
    'có tôi đi',
    'bạn có bận không',
    'có tôi bận',
    'bạn có biết làm món này không',
    'có tôi biết',
    'bạn có thích mua sắm không',
    'có tôi thích',
    'bạn có thời gian rảnh không',
    'có tôi có',
    'bạn có khỏe không',
    'có tôi khỏe',
    'bạn đã sẵn sàng chưa',
    'sẵn sàng rồi'
  ];
  static List<String> dao = [
    'muồi cóng tú tiếng anh nhe',
    'dia ứ cóng tú nao bé tỏ dia lổng thiết bị hỗ trợ',
    'muồi nhây búa hểu há nhủng',
    'nhây búa hểu mùi nam',
    'muồi nhây piáo diêm ha lao à',
    'nhây piáo diêm huế',
    'muồi chấu há nhủng công',
    'dia chấu giáo viên',
    'muồi thích hốp cà phê nhe',
    'dia thích hốp cà phê nhi',
    'muồi nhản hàng đẻm nhá',
    'dia ứ cèng nhản náo',
    'muồi cần dia thếng nhe',
    'ừ dia thếng muồi',
    'muồi tú khúng nhe',
    'dia tú khúng nhê',
    'muồi mình mảng phim nhe',
    'ừ dia mình nhê',
    'muồi híu nhe',
    'ừ dia híu nhê',
    'muồi thích tộ há nhủng sâu à',
    'dia thích tộ tiểu thuyết',
    'thời tiết ì hoi duổi nhe',
    'ừ duổi nhê',
    'muồi nhản đom nhá',
    'dia ứ cèng nhản náo',
    'muồi muống nhạc nhe',
    'ừ dia muống nhê',
    'muồi mìng du lịch nhe',
    'dia mìng nhi',
    'muồi thích nhản há nhủng món ăn à',
    'dia thích phở',
    'muồi ói hốp vuôm nhe',
    'ừ dia ói hốp nhi',
    'muồi mảng chương trình ti vi nhá',
    'dia cứ cèng mảng náo',
    'muồi híu địa chỉ nhe',
    'dia híu nhê',
    'muồi thếng dia tú nhe',
    'ừ dia thếng tú nhi',
    'muồi thích chơi thể thao nhe',
    'ừ dia thích nhi',
    'muồi ói puồng dia nhe',
    'ừ dia ói nhi',
    'muồi mảng tin tức nhe',
    'ừ dia mảng nhi',
    'muồi mìng chấu công diếu nhe',
    'ừ mìng diếu nhi',
    'muồi bận nhe',
    'ừ dia bận nhi',
    'muồi hài chấu nái nhủng món ăn nhe',
    'dia hài nhi',
    'muồi thích mìng mái đồ nhe',
    'dia thích nhi',
    'muồi mài thời gian rảnh nhe',
    'ừ dia mài nhi',
    'muồi lống nhe',
    'ừ dia lống nhi',
    'muồi sẵn sàng nhá',
    'dia sẵn sàng nhá'
  ];
  static List<String> anh = [
    'can you speak english',
    'no i cant but i can use supportive devices',
    'whats your name',
    'my names nam',
    'where are you from',
    'im from hue',
    'what do you do',
    'im a teacher',
    'do you like coffee',
    'yes i do',
    'have you had breakfast',
    'no i havent',
    'do you need some help',
    'yes i do',
    'do you have any free time',
    'yes i do',
    'do you go to the cinema',
    'yes i do',
    'do you know it',
    'yes i do',
    'what kinds of book do you like to read',
    'i like novel',
    'is the weather nice today',
    'yes it is',
    'do you have lunch',
    'no i dont',
    'do you listen to music',
    'yes i do',
    'do you go travel',
    'yes i do',
    'what kinds of food do you like to eat',
    'i like noodle',
    'would you like some water',
    'yes please',
    'do you watch the program',
    'no i dont',
    'do you know the address',
    'yes i do',
    'can you help me',
    'yes i can',
    'do you like sports',
    'yes i do',
    'do you want to see me',
    'yes i do',
    'do you watch the news',
    'yes i do',
    'do you go to work early',
    'yes i do',
    'are you busy',
    'yes i am',
    'do you know how to make this dish',
    'yes i do',
    'do you like shopping',
    'yes i do',
    'do you have free time',
    'yes i do',
    'how are you',
    'im fine thank you',
    'are you ready',
    'yes i am'
  ];
  static List<String> pathen = [
    'mùng pi tứ tiếng anh là',
    'mua giào  hù mũ hỗ trợ ninh nhà ý tứ là',
    'ma bu gẫy già',
    'ma bũng ý nam ní',
    'mũng thà xã ti a',
    'mũng thòng huế ti ní',
    'mùi ý cũng a gia',
    'vòi ý cô giảo mà',
    'mủng vớ óc cà phê là',
    'vớ óc cà phê mà',
    'bản mủng no ý cả tí pấy',
    'nói ý trinh và',
    'mù póng và tứ là',
    'tứ mà',
    'múng hi mi thời gian lả',
    'vò mi thời rang lả',
    'mủa nhi sao tăng ngọ lạ',
    'voi nhi mà',
    'mủ pi tứ lạ',
    'vò pi tứ nhạ',
    'mù vơ tơ sí là',
    'vò vớ thợ tiểu thuyết mà',
    'mi ăng ngo ù  a',
    'ni  ăng ngo ù lắng',
    'hi non sò vả',
    'và sung no ý',
    'mù vớ má nhạc là',
    'vò má mà',
    'mủ vớ nhi du lich à',
    'vò nhi mà',
    'mủ vân hỏa gia',
    'mò vấn no bủn',
    'mủ óc o là',
    'vỏ ó o mà',
    'mủa sao tăng ngọ va',
    'chua xìn nhi',
    'muti tứ a số là',
    'và tí tứ mà',
    'mù   póng va tứ là',
    'vò póng tứ mà',
    'mủ vớ thể thao là',
    'vò vớ thể thao mà',
    'mủng vớ chế vò là',
    'vò vờ chè mủng mà',
    'mủ tí tứ a số là',
    'vò ti tứ mà',
    'mủ nhì ý cung chu là',
    'vò nhi ý cung mà',
    'hi nhi ý cúng lả',
    'hi vòng mi cũng trong',
    'mủ tí tứ ý hót vi là',
    'vò nhi mà',
    'mủ vớ nhi già hơ là',
    'vò nhi mà',
    'mủ mi thời gian là',
    'vò chử chờ nhi mà',
    'mủng giẻ là',
    'vòn giẻo ma',
    'mủa chụ bị sing là',
    'chu bị sing á ne'
  ];

  static void showLoadingDialog(BuildContext context, String text) {
    showDialog(
      context: context,
      barrierDismissible: false, // Prevent user from dismissing the dialog
      builder: (BuildContext context) {
        return Dialog(
          child: Padding(
            padding: const EdgeInsets.all(16.0),
            child: Row(
              mainAxisSize: MainAxisSize.min,
              children: [
                const CircularProgressIndicator(
                  color: Colors.orange,
                ),
                // Display a circular progress indicator
                const SizedBox(width: 16.0),
                Text(text),
                // Display a text message
              ],
            ),
          ),
        );
      },
    );
  }

  static void hideLoadingDialog(BuildContext context) {
    Navigator.of(context).pop(); // Close the dialog
  }

  static void showAlertDialog(
      BuildContext context, String title, String content) {
    showDialog(
      context: context,
      builder: (BuildContext context) {
        return AlertDialog(
          title: Text(title),
          content: Text(content),
          actions: <Widget>[
            TextButton(
              child: const Text("OK"),
              onPressed: () {
                Navigator.of(context).pop(); // Close the dialog
              },
            ),
          ],
        );
      },
    );
  }
}
