import 'package:flutter/material.dart';

class Common {
  Common._();

  static List<String> kinh = [
    'chào bạn',
    'hẹn gặp lại',
    'bạn khỏe không',
    'hôm nay bạn thế nào',
    'gia đình bạn khỏe không',
    'bạn đang làm gì vậy',
    'dạo này công việc của bạn thế nào',
    'cảm ơn bạn nhiều nhé',
    'xin lỗi tôi đến muộn',
    'không sao đâu',
    'cái này bao nhiêu tiền',
    'có giảm giá không',
    'tôi muốn mua cái này',
    'bạn ăn cơm chưa',
    'đồ ăn hôm nay ngon quá',
    'cho tôi một cốc cà phê nhé',
    'làm ơn chỉ cho tôi đường đến bến xe',
    'đi xe máy hay ô tô tiện hơn',
    'mấy giờ rồi',
    'hôm nay là thứ mấy',
    'ngày mai bạn rảnh không',
    'mời bạn ăn cơm',
    ' cảm ơn bạn tôi ăn rồi',
    ' hôm nay ăn gì nhỉ',
    ' món ăn này ngon quá ',
    ' mời bạn thêm một chút nữa nhé',
    'món này vừa miệng quá',
    'tôi no rồi cảm ơn',
    'bạn thích ăn cay không',
    'chúc bạn ăn ngon',
    'ăn cơm trưa chưa',
    'món này làm từ gì thế',
    'bạn có muốn thử món này',
    'quê bạn ở đâu',
    'quê bạn có gì đặc biệt không',
    'bạn có thể kể về quê hương của mình không',
    'quê bạn có món ăn đặc sản nào không',
    'ở quê bạn có lễ hội gì thú vị không',
    'quê bạn có cảnh đẹp nào nổi tiếng không',
    'bạn thường về quê vào dịp nào trong năm',
    'người dân ở quê bạn thường làm nghề gì',
    'ở quê bạn có nhiều cây cối không',
    'quê bạn có những truyền thống nào đáng nhớ',
    'bạn đã sống ở quê bao lâu rồi',
    'quê bạn có chợ hoặc khu mua sắm nào nổi tiếng không',
    'ở quê bạn có phong tục nào đặc biệt không',
    'bạn có thể kể về một lễ hội truyền thống ở nơi bạn sống không',
    'bạn có biết những tập quán cưới hỏi ở quê mình không',
    'bạn có thường tham gia các lễ hội ở quê không',
    'mùa nào trong năm ở quê bạn có nhiều phong tục đặc sắc',
    'quê bạn có những ngày lễ lớn nào trong năm',
    'tết nguyên đán ở quê bạn có gì khác biệt so với nơi khác không',
    'có những phong tục đặc biệt khi sinh con ở quê bạn không',
    'bạn có nhớ những tập quán của gia đình mình khi còn nhỏ không',
    'quê bạn có món ăn đặc sản nào nổi tiếng không',
    'bạn thích món ăn nào nhất trong ẩm thực quê mình',
    'ở quê bạn món ăn nào thường được ăn vào dịp lễ tết',
    'bạn có thể giới thiệu một món ăn truyền thống của quê bạn không',
    'ở quê bạn món ăn nào được chế biến từ những nguyên liệu tự nhiên',
    'quê bạn có những loại trái cây nào đặc biệt',
    'món ăn quê bạn có thể tìm thấy ở đâu ngoài địa phương',
    'quê bạn có món ăn nào ăn kèm với nước chấm đặc biệt không',
    'bạn có thường ăn các món ăn đặc biệt vào mùa nào trong năm không',
    'bạn có thường xuyên tập thể dục không',
    'bạn có bị ốm gần đây không',
    'bạn ăn uống có điều độ không',
    'bạn có uống đủ nước mỗi ngày không',
    'bạn có thói quen ngủ đủ giấc không',
    'bạn có hay gặp vấn đề về sức khỏe không',
    'bạn có thường xuyên kiểm tra sức khỏe định kỳ không',
    'bạn có sử dụng các phương pháp chữa bệnh tự nhiên không',
    'bạn có bị dị ứng với bất kỳ thứ gì không',
    'bạn có biết cách giảm căng thẳng không',
    'bạn có ăn đủ các loại thực phẩm giàu vitamin không',
    'bạn có uống thuốc hay bổ sung vitamin gì không',
    'bạn có hay đi bộ hoặc chạy bộ ngoài trời không',
    'bạn có thích ăn thực phẩm hữu cơ không',
    'gia đình bạn có mấy người',
    'bạn có anh chị em không',
    'bạn sống với ai trong gia đình',
    'ba mẹ bạn làm nghề gì',
    'bạn có thường xuyên gặp gỡ gia đình không',
    'gia đình bạn có hay tổ chức các buổi họp mặt không',
    'bạn có thể kể về một kỷ niệm đáng nhớ với gia đình không',
    'bạn thích làm gì cùng gia đình vào cuối tuần',
    'mỗi lần lễ tết gia đình bạn thường làm gì',
    'bạn có bao giờ cảm thấy căng thẳng với gia đình không',
    'gia đình bạn có truyền thống gì đặc biệt không',
    'bạn có được giáo dục như thế nào từ gia đình',
    'bạn có quý trọng những gì từ gia đình mình không',
    'bạn có hay chia sẻ các vấn đề cá nhân với gia đình không',
    'trong gia đình bạn ai là người bạn thân nhất',
    'tôi thường xuyên tập thể dục vào sáng sớm đi bộ hoặc chạy bộ để giữ cơ thể khỏe mạnh',
    'gần đây tôi không ốm sức khỏe khá ổn',
    'tôi cố gắng ăn uống đầy đủ các nhóm thực phẩm để duy trì sức khỏe',
    'tôi thường ngủ đủ  tiếng mỗi ngày điều này giúp tôi cảm thấy tỉnh táo',
    'tôi ít khi gặp vấn đề về sức khỏe nhưng tôi luôn kiểm tra sức khỏe định kỳ để phòng ngừa',
    'bạn nên ngủ sớm',
    'màu yêu thích của tôi là màu xanh nó mang lại cảm giác bình yên và thư giãn',
    'tôi thích màu sáng hơn vì chúng tạo không gian thoáng đãng và tươi mới',
    'tôi thích phối màu khi trang trí đặc biệt là màu sắc đối lập để tạo điểm nhấn',
    'màu đỏ là màu tôi thấy may mắn nó tượng trưng cho sự may mắn và thành công',
    'gia đình tôi có bốn người ba mẹ và tôi tôi là con một',
    'tôi có một người anh và một người em chúng tôi rất thân thiết với nhau',
    'ba mẹ tôi làm công việc văn phòng họ luôn dạy tôi về tầm quan trọng của học hành',
    'tôi rất thích dành thời gian cuối tuần với gia đình thường là đi ăn hoặc xem phim cùng nhau',
    'kỷ niệm đáng nhớ nhất là khi cả gia đình tôi đi du lịch biển vào mùa hè năm ngoái',
    'tôi học tại trường thpt hiện đang học lớp ',
    'tôi rất thích môn toán vì nó giúp tôi rèn luyện tư duy logic',
    'trường tôi có nhiều hoạt động ngoại khóa thú vị như câu lạc bộ âm nhạc và thể thao',
    'kỷ niệm đáng nhớ nhất của tôi là lần tham gia kỳ thi học sinh giỏi và đạt giải cao',
    'tôi thích trường của mình vì thầy cô rất tận tâm và bạn bè luôn giúp đỡ nhau',
    'tôi yêu trường của tôi',
    'quê tôi ở nghệ an nổi tiếng với các món ăn đặc sản như cháo lươn và mắm tôm',
    'quê tôi có nhiều cảnh đẹp tự nhiên đặc biệt là bãi biển cửa lò rất nổi tiếng',
    'tôi luôn nhớ về quê nhà mỗi khi xa nơi đó có những người thân yêu và không khí trong lành',
    'vào dịp tết cả gia đình tôi thường quây quần bên nhau cùng ăn các món ăn truyền thống như bánh chưng thịt kho',
    'quê tôi có những lễ hội rất đặc sắc như lễ hội đền hùng thu hút rất nhiều du khách',
    'quê tôi có phong tục thờ cúng tổ tiên rất quan trọng đặc biệt là vào dịp tết nguyên đán',
    'trong gia đình tôi mỗi dịp tết chúng tôi đều làm bánh chưng và tổ chức cúng tổ tiên',
    'món ăn đặc sản của quê tôi là phở mỗi lần về quê tôi luôn ăn món này',
    'ở quê tôi vào dịp lễ hội người dân thường làm những món ăn đặc biệt như chè trôi nước xôi vò',
    'mùa hè ở quê tôi rất thích hợp để ăn các loại trái cây như xoài ổi và dưa hấu',
    'tôi nấu ăn ngon lắm',
    'tôi thường ăn sáng với bánh mì hoặc phở rất nhanh gọn nhưng đầy đủ năng lượng',
    'món ăn tôi thích nhất là cơm rang vì nó vừa ngon lại dễ làm',
    'hôm nay gia đình tôi ăn món cá kho rất hợp khẩu vị',
    'món ăn yêu thích của tôi là bún chả tôi rất thích ăn món này vào những ngày hè nóng bức',
    'mỗi bữa tối tôi thường ăn món nhẹ như canh rau thịt luộc rất dễ tiêu hóa',
    ' tôi thích ăn thịt gà',
    'tôi không đói',
    'tôi thích ăn xoài',
    'tôi thích dưa hấu nhất là vào mùa hè',
    'táo ngọt và giòn',
    'chanh rất chua',
    'sầu riêng nổi tiếng ở miền nam',
    'vải thiều đến từ bắc giang',
    'cam thường ép lấy nước',
    'bơ có thể ăn với đường hoặc làm sinh tố',
    'dâu tây nhỏ và có màu đỏ',
    'mít có mùi thơm đặc trưng',
    'tôi thích chó vì chúng trung thành',
    'tôi thích mèo vì chúng dễ thương',
    'hổ rất mạnh mẽ và dũng cảm',
    'voi to lớn và hiền lành',
    'cá sống dưới nước',
    'chim sống trên cây',
    'gà cho trứng và thịt',
    'trâu giúp cày ruộng',
    'chó sủa gâu gâu',
    'mèo kêu meo meo',
    'đi bộ',
    'chạy',
    'nhảy',
    'ngồi',
    'đứng',
    'ngủ',
    'ăn',
    'uống',
    'đọc',
    'viết',
    'nói',
    'nghe',
    'nhìn',
    'thấy',
    'nói chuyện',
    'hét lên',
    'thì thầm',
    'hỏi',
    'trả lời',
    'cười lớn',
    'khóc',
    'giữ',
    'nắm lấy',
    'đẩy',
    'kéo',
    'ném',
    'bắt',
    'vỗ tay',
    'cười mỉm',
    'ngáp',
    'duỗi người',
    'vẫy tay',
    'ôm',
    'hôn',
    'gật đầu',
    'lắc đầu',
    'vẽ tranh',
    'nhảy múa',
    'hát',
    'chơi',
    'xây dựng',
    'sửa chữa',
    'nấu ăn',
    'núi',
    'sông',
    'hồ',
    'biển',
    'rừng',
    'bãi biển',
    'sa mạc',
    'đồi',
    'thung lũng',
    'thác nước',
    'đồng bằng',
    'hang động',
    'vách đá',
    'đảo',
    'cây',
    'hoa',
    'cỏ',
    'bầu trời',
    'mây',
    'mặt trời',
    'mặt trăng',
    'ngôi sao',
    'trái đất',
    'cánh đồng',
    'con đường',
    'lối đi',
    'cầu',
    'thị trấn',
    'làng',
    'bạn',
    'tên',
    'bạn',
    'bạn',
    'mình',
    'cảm ơn',
    'không',
    'xin',
    'tôi',
    'làm',
    'bạn',
    'tôi',
    'hẹn',
    'chào',
    'chúc',
    'bảo',
    'mấy',
    'cái',
    'anh',
    'mình',
    'trường học',
    'lớp học',
    'giáo viên',
    'học sinh',
    'bàn học',
    'ghế',
    'bảng đen',
    'bảng trắng',
    'bút',
    'bút chì',
    'cục tẩy',
    'sách',
    'vở',
    'môn học',
    'bài học',
    'bài tập về nhà',
    'kỳ thi',
    'kiểm tra',
    'điểm',
    'cặp sách',
    'đồng phục',
    'hiệu trưởng',
    'hiệu phó',
    'bạn học',
    'thư viện',
    'phòng tập thể dục',
    'máy tính',
    'máy in',
    'bản đồ',
    'phấn',
    'thước kẻ',
    'lịch',
    'đèn bàn',
    'mỹ thuật',
    'khoa học',
    'lịch sử',
    'toán học',
    'văn học',
    'địa lý',
    'ngữ văn',
    'giáo dục thể chất',
    'sức khoẻ',
    'bác sĩ',
    'y tá',
    'bệnh viện',
    'phòng khám',
    'hiệu thuốc',
    'thuốc',
    'điều trị',
    'đơn thuốc',
    'căn bệnh',
    'bệnh',
    'đau',
    'sốt',
    'cảm lạnh',
    'ho',
    'đau đầu',
    'đau bụng',
    'viêm họng',
    'chấn thương',
    'phẫu thuật',
    'ca mổ',
    'hồi phục',
    'tiêm phòng',
    'kiểm tra sức khoẻ',
    'huyết áp',
    'xét nghiệm máu',
    'chụp xquang',
    'xe cấp cứu',
    'sơ cứu',
    'bảo hiểm sức khoẻ',
    'tập thể dục',
    'chế độ ăn uống',
    'dinh dưỡng',
    'thể hình',
    'giảm cân',
    'giấc ngủ',
    'sức khoẻ tâm thần',
    'căng thẳng',
    'lo âu',
    'trầm cảm',
    'thư giãn',
    'vệ sinh',
    'khoẻ mạnh',
    'ốm',
    'yêu cầu',
    'hỏi',
    'đòi hỏi',
    'mong muốn',
    'hy vọng',
    'khao khát',
    'làm ơn',
    'bạn có thể',
    'bạn có thể làm ơn',
    'bạn có thể giúp tôi',
    'cho phép tôi',
    'tôi muốn',
    'tôi cần',
    'tôi muốn nói',
    'bạn có phiền không',
    'có thể không',
    'xin phép',
    'tôi cầu xin',
    'tôi hy vọng',
    'tôi mong',
    'bạn làm ơn giúp tôi',
    'tôi rất cảm ơn',
    'có thể giúp tôi không',
    'xin vui lòng',
    'giúp tôi nhé'
  ];
  static List<String> dao = [
    'muồi mình hải',
    'hải chản túch cúng tài dẻo',
    'muồi lống nhe',
    'ì hoi muồi lống nhe',
    'muồi nhây péo nhổ lổng nhe',
    'muồi đang tấu hái nhủng à',
    'thảm muồi tấu hái nhủng à',
    'cảm ơn muồi ná',
    'dia thô tài tủn tấy',
    'lắm pút tẩy nao',
    'nòng pây tiền nhàn',
    'muồi ánh mảy tẩu tấy tú nhe',
    'dia ói mái tom cả nái',
    'muồi nhẻ háng nhá',
    'ì hoi nhẻn háng khu quá',
    'muồi pha pu dia cốc cà phê',
    'muồi chỉ tóng pi dia tháo bến xe',
    'theo muồi mình ô tô hay xe máy tiện hơn',
    'ì ít pia tấy giờ',
    'ì hoi thứ háy nhủng',
    'dang hoi bản tấu háy nhủng nhe',
    'bạn phá nhẻn háng á',
    'tôm má dia nhiển lồi',
    'nay hoi muồi nhiện cái nhủng',
    'nay món khô kềnh',
    'ánh nhẹn thêm tấy',
    'món nhẹn khô quá',
    'dia pếu luôi',
    'muồi nhiện tu bẹn nải',
    'muồi nhiện khô mải',
    'muồi nhiện háng bẻn canh',
    'nay mon chấu bằng cái nhậu nha',
    'muồi ói nhiển nay món ải ',
    'muồi  nhây quê ố tram',
    'muồi nhây quê mại cay nhủng đặc biệt ải',
    'muồi kể muồi nhe tóng dai tảng hải à',
    'muôi nhây quê mài cay nhủng món đặc sản ải',
    'muồi nhây quê mài cáy nhủng lễ hội',
    'dia muồi lải mài hái nhủng duổi nhe',
    'muồi o duấn peo mại',
    'peo muồi hay chấu cáy nhủng ',
    'muồi peo mại cham đéng ải',
    'dia muồi lải mài hái nhủng pìa lại hoi nhay',
    'muồi dia lại a tóng lào há kẹng',
    'muồi peo mài chợ ai',
    'dia muồi lại mài hái nhủng đặc biệt nhây',
    'muồi nhây peo mài cáy nhủng phong tục ải ',
    'muồi nhi peo mai nhi thức nào đặc biệt ải ',
    'muồi nhi peo mài cái nhủng phong tục ',
    'muồi cói mình hang lễ hội ải ',
    'dia muồi nhây quê tháo dàng mài hái nhủng hai dây',
    'muồi nhây que mài cáy nhủng lễ hội mài ',
    'muồi nhây nháng mài cáy nhủng đặc biệt ải',
    'muôig chảng  tập tục muồi nhây phì đảng phái nhây',
    'muồi nhây quê mài món cáy nhủng đặc sản ải',
    'muồi ói nhiển món ó quê ải',
    'muồi nhây quê hay nhẹn món cáy nhủng ố chiêm ',
    'muồi giới thiệu nhẹn hốp bun dia tấy',
    'dia muồi dia táo mài hái nhủng nhạn từ kèm đia',
    'muồi nhây quê mày cáy nhủng piêu mại',
    'muồi nhây quê lo puột cáy nhủng món ô cang',
    'dia muồi nhây quê mài hái nhủng nhại tấu chấm khu',
    'muồi ói nhiển cáy nhủng đặ biệt ải',
    'muồi hay mình tập thể dục ải ',
    'muồi hay bị pút ải',
    'muồi nhẹn húp đều ải',
    'muồi húp vuông đủ ải',
    'muồi puối lấu ải',
    'muồi mấy bị pí nạ ải ',
    'muồi hay mình khám đèo ải',
    'muồi tùa tậu bệnh bằng kèm đia à',
    'muồi bị dị ứng cáy nhủng mải ',
    'muồi hiu cáy nhủng chấu giảm căng thẳng ải ',
    'muồi nhẹn đủ vitamin ải ',
    'muồi hốp đia hay bổ sung vitamin ải',
    'muồi hay mình bộ hay thíu ại',
    'muồi ói thích ẩm thực ải',
    'muồi nhây peo mài pây chía miền ',
    'muồi có em hay ỉ ải',
    'muồi ố chón căm tào ',
    'tía má muồi chẩu cáy nhủng',
    'muồi  hay gặp tía  mả mại',
    'muồi nhây peo hay họp mại',
    'muồi kể pun dia muống chiêm phi đảng phái',
    'muồi thịch chảu cáy nhủng chón muồi nhây peo',
    'nháng muồi chón gia đình hay châu cáy nhủng ',
    'muồi hay puột căng thẳng ải ',
    'muồi nhay peo mại cáy nhủng đặc biêtj',
    'muồi tu gia đình giáo dục phí nạ ',
    'muồi muồi hám muồi nhây peng nua nhe',
    'muồi hay  cong vạ chón gia đình ải',
    'muồi nhây peo cằng tào thân chói mùa nhất',
    'dia ờ lẩu chập thể dục đom diếu minh bộ sai bẹ thíu pùn miền hên',
    'tơ xảm diêm mái pus tẻng lổng hên nhây',
    'dia nhẹn hốp đầy đủ',
    'dia ờ lủng puồi cảng tiếng dịa hoi nìn nỉnh táo  chẩu hay ',
    'dia má tpú tẻng ta nao máy toi dia à lẩu mình khám kiểm tra sức khỏe',
    'muồi ói puối siếp',
    'dia thích màu meng dia hái màu meng ',
    'dia thích màu sáng hơn dia hải thoải mái',
    'dia thích phối màu trang trí ',
    'dia hải màu đỏ be màu may mắn  nìn tượng phun may mắn kéo thành công',
    'dia nhây peo mại pia tam men ',
    'dịa mai pị trón em ',
    'dia nhây tía mạ chẩu văn phòng ',
    'muồi nhây kỉ niệm muồi chón gia đình ',
    'muồi nhây kỉ niêm muồi chón gia đình mình du lịch',
    'dia đang học lớp ',
    'dia rất thích tồ môn toán ',
    'dia nhây trường mại cham hoạt động ngoại khóa ',
    'dia nhây kỷ niệm khi minh thi học sinh giỏi ',
    'dia thích dia nhây trường',
    'dia thích nhi nha trường',
    'dia nhây quê ố nghệ an ',
    'dia nhây quê mài cham cảnh đẹp ',
    'dìa dủn nình cô dia cháng péo diêm lại mài nhây người thân ',
    'pìa nháng dia nhây gia đình thường họp ',
    'nhây péo mài xam lễ hội đại haudẩy thắm miền tham gia',
    'nhây quê hương mài phong tuc thờ cúng tổ tiên',
    'muồi  nhay quê hay sít miên ải',
    'choải nhám dia nhây peo thường chấu dúa ',
    'dia nhây quê pủn là đặc sản',
    'mùa hè nhây quê hương mày đẩy xăn piêu',
    'dia tấu há nghiện cố',
    'dia nhẹn dúa chon pún pia nhang đong',
    'dia ói nhẹn khẩu khủa',
    'nay hoi dia nhiện peo nhiện beo',
    'dia thích nhiện bún chả ',
    'lùng muống dia ói nhiện lai ó luộc chón lai',
    'dia muốn ói nhẹ chai ó',
    'dia mấy ngọ nâu',
    'dia ói nhặn xoài',
    'dia ói nhặn piếu dưa hâu laiói tháo co má ',
    'táo nhạn nhái nhạn piếu giòn hậy',
    'nhặn quả chanh xui hây ',
    'dia nại sầu riêng nọi tiếng nạ ố vằn miền nam',
    'a nhu a nhù vải thiều pại',
    'dấu mấy cam nạy cái chẩu nan chẩu huôm',
    'nhặn quả bơ cáp đường hoặc dấu sin tố',
    ' chớ dâu tây sí en mái sĩ',
    'mắc mị piếu nhằn hằng đang pậy',
    'dia ói thích ụng chú óng hậy',
    'dia ói thích úng lồm đại cá úng lồm',
    'ha mao ca día ha mao',
    'nái tạo con voi hám niền ',
    'beo diên ca tía duông',
    'nọ diêm chia đê áng',
    'chài ò nền dè chảo diềm lẹ o',
    'muồi mài ngùng so lình ruộng',
    'pây tàn chú ngạt muồi gâu gâu',
    'ma lồng hệu meo meo',
    'mình dạo',
    'thỉu',
    'thiu',
    'duôi',
    'xâu',
    'puổi',
    'nhẹn',
    'hốp',
    'tổ xâu',
    'khia xâu',
    'phu',
    'móng',
    'mạng',
    'puộn nhe',
    'cong vạ',
    'hệu',
    'cong bạ phải',
    'nại muồi',
    'muồi cong',
    'chắc',
    'nhiếp',
    'nan',
    'nan lậu',
    'nhi phông',
    'peng',
    'phếnh',
    'sang so',
    'vai pua',
    'chác',
    'ngáp',
    'pút luội',
    'vạy pua',
    'hóp',
    'yên hăm',
    'khẩy ngon',
    'hạ ngon',
    'muồi vẽ',
    'tèo',
    'páo dung',
    'mình dạo',
    'xậu páo',
    'sọ',
    'sâu hảng',
    'kềm',
    'vồm tông',
    'vò meng',
    'biển',
    'kềm',
    'bãi biển',
    'sa mạc',
    'kềm',
    'thung lũng',
    'vòm thác',
    'đào pèng',
    'đào lạng',
    'vènh pẹ',
    'đảo',
    'giảng',
    'pèng',
    'mia',
    'pò hoi',
    'lùng beng',
    'pò hoi',
    'hả',
    'suất sao',
    'đia đao',
    'há lang',
    'chao',
    'chào mình',
    'chiều',
    'tồm lang',
    'mua dao',
    'tồng nìn',
    'búa',
    'tồng nìn',
    'tồng nìn',
    'muồi',
    'cảm ơn',
    'mí mài',
    'thô',
    'dia',
    'dâu công',
    'tồng nìn',
    'dia',
    'dia puông',
    'chào',
    'chúc muồi',
    'día púa muồi',
    'nóng mấy',
    'nong',
    'có',
    'dia',
    '    cong nong trường ',
    'nong lớp',
    'giaos viên',
    'chuôi',
    'bàn học',
    'hẩy tôn',
    'thầy bảng',
    'bảng phia',
    'bút',
    'bút chì',
    'cục tẩy',
    'sâu',
    'sâu phia',
    'môn',
    'bài sâu',
    'duổn pao la',
    'ghét muồi',
    'mạng muồi',
    'điểm',
    'bụa sâu',
    'đồng phục',
    'hiệu trưởng',
    'hiệu phó',
    'tùng nìn',
    'thư viện',
    'phòng tập thể dục',
    'máy tính',
    'máy in',
    'bản đồ',
    'phấn',
    'thước kẻ',
    'lịch',
    'âu tang',
    'mỹ thuật',
    'khoa học',
    'lịch sử',
    'toán học',
    'văn học',
    'địa lý',
    'ngữ văn',
    ' giáodục thể chất',
    'mảy xa ne',
    'bác sĩ',
    'y tá',
    'bệnh viện',
    'phòng khám',
    'hiệu thuốc',
    'thuốc',
    'mình xọ bệnh',
    'đia',
    'bệnh nhè',
    'pus bệnh',
    'mun',
    'đang pu chóa',
    'đang pú chóa',
    'đang pút hốp',
    'gong mun',
    'kề xi mun',
    'chang mun',
    'dia chang mun',
    'đang mì phải',
    'đang phái',
    'diêm lống lá',
    'mình tiêm',
    'nhi khám',
    'huyết áp',
    'do diem',
    'chụp xquang',
    'cho xe minh kham',
    'sơ cứu',
    'bảohiểm sức khoẻ',
    'tập thể dục',
    'đang nhẹn',
    'nhen xang',
    'thể hình',
    'dia giảm',
    'dia puổi tớ tẩy á',
    'pu tin',
    'căng thẳng',
    'dào',
    'pha chẹ',
    'má hai dào',
    'puốt đao',
    'dia đang mài sạ',
    'đang di tang pút pẻng',
    'mình thỉnh công',
    'nại muồi',
    'toi muồi',
    'đang lác',
    'hy vọng',
    'khao khát',
    'làm ơn',
    'bạn có thể',
    'bạn có thể làm ơn',
    'mình thỉnh dia tu dẹ',
    'muồi pun dia he',
    'muồi pun dia',
    'dia muồn puôi duổi',
    'dia nại muồi',
    'muồi tua củng nhe',
    'tu nhẹ',
    'tho muôi',
    'tho',
    'diếm oi',
    'dia ỏi',
    'muồi thỉnh nhi',
    'dia pong vai',
    'muồi thinh dia',
    'dia hai dạo',
    'thỉnh dia'
  ];
  static List<String> anh = [
    'hello',
    'see you again',
    'how are you',
    'hows your day',
    'is your family doing well',
    'what are you doing',
    'how is your work going today',
    'thank you very much',
    'sorry im late',
    'no worries',
    'how much is this',
    'can you lower the price',
    'i want to buy this one',
    'have you eaten yet',
    'the food is so delicious today',
    'please get me a cup of coffee',
    'please take me to the bus station',
    'which car is cheaper',
    'what time is it now',
    'what day are you free',
    'please come eat',
    'thank you ive eaten',
    'what are we eating today',
    'this food is so good',
    'have a bit more',
    'this dish tastes great',
    'im done thank you',
    'do you like spicy food',
    'enjoy your meal',
    'have you tried sour soup',
    'how is this dish made',
    'do you like this dish',
    'where is your hometown',
    'is there anything special about your hometown',
    'does your hometown have any special features',
    'do you usually talk to others about your hometown',
    'are there any unique customs in your hometown',
    'what do you think is most special about your hometown',
    'do you often visit your hometown',
    'in which season is your hometown most beautiful',
    'what is the most famous dish in your hometown',
    'what time of the year do you often return to your hometown',
    'what jobs are most common in your hometown',
    'are there many festivals in your hometown',
    'are there any famous stories or legends in your hometown',
    'what do you miss most about your hometown',
    'are there any specialties in your hometown',
    'do you usually recommend your hometown to friends',
    'do you know many neighbors in your hometown',
    'are there any beautiful places in your hometown',
    'what are your best memories of your hometown',
    'do you remember the games you played as a child in your hometown',
    'is there any special skill unique to your hometown',
    'are there traditional costumes in your hometown',
    'which season do you feel best represents your hometown',
    'are there unique holidays or tet traditions in your hometown',
    'what are the typical dishes of your hometown during tet',
    'are there stories about your hometown passed down through generations',
    'what local ingredients make the food in your hometown special',
    'is there a fruit or crop that your hometown is famous for',
    'do you know of any special natural landmarks in your hometown',
    'is there any local art or craft that is distinctive',
    'what seasons do people often farm in your hometown',
    'does your hometown have forests or rivers nearby',
    'do you often get sick these days',
    'are you currently taking any medication',
    'do you drink enough water every day',
    'do you have a habit of staying up late',
    'have you had any recent health checkups',
    'do you regularly check your health status',
    'do you use natural methods to treat illnesses',
    'do you take care of your physical health',
    'do you know any tips to stay fit',
    'do you consume foods rich in vitamins',
    'do you take vitamin supplements',
    'do you enjoy outdoor activities',
    'do you often eat organic food',
    'are you on a diet',
    'do you exercise every day',
    'what sports do you play',
    'does your family frequently gather together',
    'does your family often host cozy dinners',
    'does your family organize picnics or outings',
    'does your family usually meet on weekends',
    'do you celebrate holidays with your family',
    'what are some traditions unique to your family',
    'what does your family often do during vacations',
    'does your family have any special traditions',
    'how did you get your education from your family',
    'what do you value from your family',
    'do you often share personal problems with your family',
    'who is your best friend in your family',
    'i regularly exercise early in the morning walk or jog to keep my body healthy',
    'i havent been sick lately my health is quite good',
    'i try to eat a full diet of food groups to maintain my health',
    ' i usually sleep a full  hours a day which helps me feel awake',
    'i rarely have health problems but i always have regular health checkups as a precaution',
    'you should go to bed early',
    'my favorite color is blue it gives a sense of peace and relaxation',
    'i prefer lighter colors because they create an airy and fresh space',
    'i like color schemes when decorating especially contrasting colors to create accents',
    'red is the color i feel lucky it symbolizes luck and success',
    'my family has four people my parents and me i am the only child',
    'i have an older brother and a younger brother we are very close to each other',
    'my parents work in the office they always teach me about the importance of education',
    'i enjoy spending weekends with my family usually going out to eat or watching movies together',
    'the most memorable memory was when my whole family went on a beach trip last summer',
    'i am studying at high school currently in grade ',
    'i really like math because it helps me practice logical thinking',
    'my school has a variety of exciting extracurricular activities such as music and sports clubs',
    'my most memorable memory is the time i took the exam as a good student and won a high prize',
    'i like my school because the teachers are very dedicated and the friends are always helping each other',
    'i love my school',
    'my hometown is in nghe an famous for specialty dishes such as eel porridge and shrimp paste',
    'my hometown has many natural beautiful scenery especially cua lo beach is very famous',
    'i always remember my hometown whenever i am far away where there are loved ones and fresh air',
    'on the occasion of tet my whole family often gathers together eating traditional dishes such as banh chung braised meat',
    'my hometown has very special festivals such as the hung temple festival which attracts a lot of tourists',
    'my hometown has a very important custom of ancestor worship especially on the occasion of the lunar new year',
    'in my family every tet holiday we make banh chung and organize ancestor offerings',
    'the specialty dish of my hometown is pho every time i go back to my hometown i always eat this dish',
    'in my hometown on the occasion of festivals people often make special dishes such as floating tea and sticky rice',
    'summer in my hometown is perfect for eating fruits such as mangoes guava and watermelons',
    'i cook very well',
    'i usually have breakfast with bread or pho which is very quick but full of energy',
    'my favorite dish is fried rice as it is both delicious and easy to make',
    'today my family eats braised fish which is very palatable',
    'my favorite dish is vermicelli i love to eat it on hot summer days',
    'every dinner i usually eat light dishes such as vegetable soup and boiled meat which are easy to digest',
    ' i like to eat chicken',
    'im not hungry',
    'i like to eat mangoes',
    'i love watermelon especially in the summer',
    'sweet and crunchy apples',
    'lemon is very sour',
    'durian is famous in the south',
    'lychee comes from bac giang',
    'orange often squeezes juice',
    'butter can be eaten with sugar or as a smoothie',
    'the strawberries are small and red',
    'jackfruit has a characteristic aroma',
    'i like dogs because theyre loyal',
    'i like cats because theyre cute',
    'tigers are very strong and brave',
    'elephants are big and gentle',
    'fish live in water',
    'birds live in trees',
    'chicken for eggs and meat',
    'buffalo helps plow the field',
    'the dog barks',
    'the cat meows',
    'walk',
    'run',
    'jump',
    'sit',
    'stand',
    'sleep',
    'eat',
    'drink',
    'read',
    'write',
    'speak',
    'listen',
    'look',
    'see',
    'talk',
    'shout',
    'whisper',
    'ask',
    'answer',
    'laugh',
    'cry',
    'hold',
    'grab',
    'push',
    'pull',
    'throw',
    'catch',
    'clap',
    'smile',
    'yawn',
    'stretch',
    'wave',
    'hug',
    'kiss',
    'nod',
    'shake',
    'paint',
    'dance',
    'sing',
    'play',
    'build',
    'fix',
    'cook',
    'mountain',
    'river',
    'lake',
    'ocean',
    'forest',
    'beach',
    'desert',
    'hill',
    'valley',
    'waterfall',
    'plain',
    'cave',
    'cliff',
    'island',
    'tree',
    'flower',
    'grass',
    'sky',
    'cloud',
    'sun',
    'moon',
    'star',
    'earth',
    'field',
    'road',
    'path',
    'bridge',
    'town',
    'village',
    'how',
    'whats',
    'where',
    'how',
    'im',
    'thank',
    'youre',
    'excuse',
    'im',
    'please',
    'can',
    'i',
    'see',
    'good',
    'have',
    'take',
    'whats',
    'how',
    'i',
    'im',
    'school',
    'classroom',
    'teacher',
    'student',
    'desk',
    'chair',
    'blackboard',
    'whiteboard',
    'pen',
    'pencil',
    'eraser',
    'book',
    'notebook',
    'subject',
    'lesson',
    'homework',
    'exam',
    'test',
    'grade',
    'schoolbag',
    'uniform',
    'principal',
    'headmaster',
    'schoolmate',
    'library',
    'gym',
    'computer',
    'printer',
    'map',
    'chalk',
    'ruler',
    'calendar',
    'desk lamp',
    'art',
    'science',
    'history',
    'mathematics',
    'literature',
    'geography',
    'language',
    'physical education',
    'health',
    'doctor',
    'nurse',
    'hospital',
    'clinic',
    'pharmacy',
    'medicine',
    'treatment',
    'prescription',
    'illness',
    'disease',
    'pain',
    'fever',
    'cold',
    'cough',
    'headache',
    'stomach ache',
    'sore throat',
    'injury',
    'surgery',
    'operation',
    'recovery',
    'vaccination',
    'checkup',
    'blood pressure',
    'blood test',
    'xray',
    'ambulance',
    'first aid',
    'health insurance',
    'exercise',
    'diet',
    'nutrition',
    'fitness',
    'weight loss',
    'sleep',
    'mental health',
    'stress',
    'anxiety',
    'depression',
    'relaxation',
    'hygiene',
    'healthy',
    'sick',
    'request',
    'ask',
    'demand',
    'wish',
    'hope',
    'desire',
    'please',
    'can you',
    'could you',
    'would you',
    'let me',
    'i want',
    'i need',
    'i would like',
    'would you mind',
    'is it possible',
    'allow me',
    'i beg you',
    'i hope',
    'i wish',
    'could you please',
    'please help me',
    'i would appreciate',
    'may i',
    'i need your help'
  ];
  static List<String> pathen = [
    'ca xin cá',
    'pu hi gia mung ta pào',
    'nhung ù lẹ',
    'ninh hi ý già',
    'nhung ù lậy',
    'ca xi cá mú í ca già',
    'ni cạy ca xi cá mú í ca già',
    'mú nhu ù nhẹ',
    'xin lỗi múng vô',
    'quá pi tư  áy gia',
    'nhi ca cho chi nha',
    'cũng giảm í mung',
    'vò vớ ni hoóc ',
    'xinh cát no i',
    'nin hi no tế cái gia',
    'cố vò no cốc cà phê ne',
    'nin hi hơ mòng nhung ti xó a',
    'nin nhi o to nhi xe máy ù hơn nà',
    'cơ trong xi',
    'ni hi cá gia',
    'pun hi múng u i gia mà',
    'ca xin cát gia í nọ',
    'ca xin cát vò no chi a ne',
    'nhin hi no á già',
    'đơ no hơn',
    'ca xi cá gio tí cha',
    'mi hớ no đơ pú',
    'vò no chi hua',
    'ca xinh cát no tức ca pìn nẹ',
    'ca xinh cá non đơ ',
    'ca xinh cát nong xòng vả',
    'ni hớ no ca gia pía a',
    'tơ xinh cá vơ no ni họ',
    'cơ xi cá mú nhu tí xá a',
    'cơ xi cá mi cá gia cho nạy',
    'ca xinh cá nhu tơ xi có lại',
    'múng cơ xinh cá mu giá đơ hơn nạ',
    'mú cơ xin cá mê ca tế vu hế',
    'ca xi cá tơ xi ù nạy',
    'ca xi cá múng pơ tớ xi pớ a',
    'mú nhu úng nha í ca gia y tư pí ca gia',
    'ca xi cá mi pa chong nẹ',
    'ca xi cá múng mi ca giá tư píe ',
    'cơ xi cá múng tứ lu nạy',
    'cơ xi cá múng pợ nhi chợ nạy',
    'múng mi me cho dân tộc la',
    'ca xi cá mi ca giá mi ù hơn nạ',
    'ca xinh cá mú nhing mơ mẹ nhẹ',
    'ca xinh cá quá nhi lễ hội cho nhẹ',
    'ca xinh cá múng nhung múng tợ múng ụ hơn nạ',
    'ca xinh cá mi ni cá lễ ù hơn na nạ',
    'cơ xinh cá  mi ca gia cho hơn mú mu mi me cho nẹ',
    'ca xinh cá mi ca chò hơn nẹ',
    'ca xinh cá mú nhu mú úng mi cá giá cho tế hi ồ',
    'mi ca giá no đơ pú lại',
    'cơ xi cá no đơ hơn la',
    'cơ xi cá nú chi vớ no cá gia lại',
    'múng xinh ca với no ghe cho lại',
    'múng xinh ca mi ca gia no cho í tư no gion',
    'ca xi cá nó hớp pa ù hơn na',
    'mung xinh ca xinh cá mo đơ ra',
    'vớ no cá già vớ chấm a gia',
    'ca xinh cá no nú chi vớ no cho ca gia',
    'ca xinh cá mii tập thể dục tư cụ á nẹ',
    'ca xinh cá múng ma nạy',
    'múng vớ no cá gia ',
    'xinh cá nú o cho lạy',
    'xinh cá múng vớ pợ nạy',
    'chinh cá múng vớ ma nẹ',
    'ca xinh cá nhi au huyết nhẹ',
    'ca xinh cá mú vớ nhi khám bệnh cho nẹ',
    'ca xi cá mú vớ như nẹ',
    'ca xi cá mà ca gia ừ là',
    'ca xi cá lai lóng péc bấu',
    'ca xi cá lay gia bấu ',
    'ca xi ca tứ nhùng ni ca như lại',
    'ca xi cá tơ hẳn cho nhẹ',
    'ca xi cá mi ca cho nhe',
    'ca xi cá mú mi quận cho lẹ',
    'ca xi cá múng vờ tơ nhe nhung cô pợ',
    'xinh cá mú xinh kí a gia ù lẹ',
    'ca xi cá mú nhung ca gia cọ pịa ',
    'ca xi cá múng với í ca gia lạy',
    'ca xinh cá múng vớ cọ pịa nhung tứ lụ',
    'ca xi cá múng vớ cọ pịa áy gia',
    'mú pợ nhú y cá gia ú pía',
    'ca xi cá múng pợ ý nhung ca giá mạ',
    'ca xi cá múng y ca gia tơ pia lại',
    'ca xi cá tứ cho nhung ù lạy',
    'ca xi cá ụ qướ may gia',
    'ca xi cá cơ mú i ca gia è',
    'ca xi cá múng ý hiu hơn na',
    'nin hi nhi chá cụ nhi cho nọ',
    'ni hi vòng ma nhung ụ',
    'ni hi vòng no ca gia vòng nó ụ ni',
    'vò vớ pớ nin hi pớ u hơn',
    'vò thém ma lẹ vò hây nhi vó cớ me ù he',
    'xi ca pớ dụ',
    'ni hi mó hốp pơ ụ nâu',
    'vò vớ hơ lơ ù hơn',
    'vò vớ xạ ni ù hơn hóc tà go ạ',
    'vò vớ ní hó vớ pú múng vớ nạy',
    'vò pượu ư ơ pí le  vò pa vò me gia vòvò lé may lé li  to',
    'vò mi le ú mi le quợu  vò giớ giá hụ quợu tà gio',
    'vò pa í cung văn phòng cá me hu vò tơ xí',
    'vò vớ ni hi ý ca gia à vờ vó ni hi gio ta ngọ',
    'vò ni hi nhi tà cái me nhi nho ù hơn hè cai cho',
    'ngò ni hi nhu cò trường thptnhu cò chự tư sĩ ',
    'vò vớ môn tóan còng hi vò hu cái me i hi logic',
    'vò mó trường mi ca gia cho hơn vò ni hi tằng câu lạc bộ hí hô',
    'ni hi vò vớ múng pu ni hi múng hi tơ sĩ nùng pí tư hơn',
    'vò vớ nhà trường thầy cô vớ pứ hơn  vớ bạn bè pứ cái me hu pứ nhi giúp tứ hơn',
    'vò vớ nhà trường thầy cô vớ pứ hơn  vớ bạn bè pứ cái me hu pứ nhi giúp tứ hơn',
    'vò nhu nghẹ an vò vớ ni hó no đơ có cháo lượn vò mắm ta ha cúng',
    'vò pượu mia ca gia ụ hơn  vò a số nhi do bãi biện cửa lò pứ dóc quá nhắt',
    'vò vớ vò nhi cu nhọ  tế mu hóp mi me vò mì không khí',
    'nú chivò puợu ni nhu ụ vò vớ ni hó cá các me ho gụchợ ge no',
    'vò nhu vò the ụ hơn nhi lế hội đền hùng vò nhu mi hu qượu',
    'vò the mi cái me i quơ dó hơn  ni hi nú chi ',
    'vò pượunú chivò pượu vớ íng quợu ninh hi cúng tổ tiên y quợu ',
    'vò vớ  no phợ  lé li nhu pứ mo húp the vò vớ no ni hoóc',
    'nhu vò the cúng nhu lễ hội vò vớ ni hoóc no như ó o chè bí',
    'qua già núng hẹo vớ no xoàiổi vò dưa hấu',
    'vò vớ chợ ni hó no đơ',
    'vò vớ ni tí no í bánh mì mú ni mú úng phở vòng vớ ý ni hoóc ụ hơn',
    'vớ no í pứ nhi xào nono đơ vớ í',
    'vò nin hi no bịa he  no đơ',
    'vò vớ no ni hóp bún chả  vò vớ no ni hóp nún co họ',
    'no ị ngó vả vò vớ ni húp nom bi đu  ghe luộc  no pớ nhi ị hơn',
    'vò vớ nong ghe kẹ',
    'xe kí lẹ',
    'vò vớ no quả xoài',
    'vò vớ no dưa hấunhu ni pây già núng hè',
    'vớ no quả táo đơ hạ',
    'mó chanh xư tế ',
    'úng mo pị tưng sầu riêng nhu miền nam',
    'mi pị vải thiều nhu bắc giang',
    'quả cam ni mí dạng o',
    'vớ no pị bơ vớ no đường vớ í ni hó sin tó',
    'ni dâu tây dứ mi tớ',
    'a pị quả mít chó đơ nhọ',
    'vò vớ ta nhó nhu niiii',
    'vò vớ ta nho',
    'ta ghe pụ ',
    'vớ ta voi hu vò nù cũng hiền',
    'ta pia ờ cò nho o ',
    'nhu o ta pa',
    'ta ke đố cú vò khe',
    'ta nhu  ni a ta vè nhi xéng hi',
    'ta nhó nùng chủ gâu gâu',
    'ta nho gá meo meo',
    'nhi chả cu nhi',
    'tờ xì dớ',
    'tơ xi nhọ',
    'tơ xi dú',
    'tơ xi sợ nha',
    'tơ xi pớ',
    'tơ xi nó i',
    'ó o',
    'tờ xi tơ xí',
    'tơ xi xạ xí',
    'tơ xi nạ cô củng',
    'tơ xi má',
    'tơ xi do múng',
    'hâu pằm pú ne',
    'tơ xi co củng',
    'tơ xi cơ múng',
    'tơ xi ý dớ cọ',
    'tơ xi ni mung',
    'tơ xi di da mung',
    'tơ xi da mung cha',
    'tơ xi gá le',
    'tơ xi khá múng hơ',
    'tơ xi dá múng khá ta phư',
    ' tơ xin đí mủng',
    'tơ xi qué mủng ne',
    'tơ xi khá mụng',
    'tơ xi chọ',
    'tơ xi vô tay',
    'tơ xi tá mung nẹ',
    'tơ xi nghè',
    'tơ xi pơ khé',
    'tơ xi chào mung ne',
    'tơ xi tau mung tạo dợ',
    'tơ xi dao mung ta dự',
    'tơ xi ngó ngó',
    'tơ xi quy chú ngu',
    'tơ xi vẽ tranh',
    'tơ xi múa văn nghệ',
    'tơ xi i xé',
    'tơ xi nhính gự',
    'tơ xi í pơ',
    'tơ xi pé',
    'tơ xi í nọ',
    'tơ duy',
    'sông',
    'hồ',
    'biển',
    'co dọ',
    'bãi biển',
    'sa mạc',
    'tơ duy',
    'thung lũng',
    'tơ o',
    'a so pỉ',
    'á khụng du',
    'pí dụ',
    'đảo',
    'tợ pạ',
    'booc',
    'sụ',
    'au ngo',
    'bú hụ',
    'an hi',
    'an lác',
    'bàu xô',
    'ca li',
    'ni thung nhi',
    'tơ cụ',
    'tơ cụ nhi',
    'tơ chớ',
    'ta chợ nhi',
    'ni khu me',
    'mung nhinh gư',
    'tơ xi quá chi',
    'mung',
    'mùng',
    'vò',
    'dạ ơn',
    'mí',
    'tơ xi dá múng qợ',
    'láy i',
    'í cúng',
    'mung',
    'lay i',
    'pơ xi tình',
    'í nha tì',
    'mủ nhung áp pủ la',
    'ti bò hụ',
    'mủng mi ge cho',
    'gá da',
    'au ú',
    'mùng',
    'a pịa tơ xí',
    'tơ xi tơ xí',
    'giaos viên',
    'ta ka',
    'ke pa tơ xí',
    'a thú',
    'a bảng',
    'pau co',
    'tơ pí',
    'pu chi',
    'cục tẩy',
    'pin đọ',
    'pi đo xạ',
    'môn',
    'tơ xi ne',
    'tơ xi tơ xi',
    ' tơ xi thị',
    'cha mủng',
    'mung điểm',
    'a thứ',
    'kế ợ',
    'hiểu trưởng',
    'hiệu phó',
    'dao mủng tớ xí',
    'a pìa đọ',
    'a pịa tơ ni pia tơ thể dục',
    'máy tính',
    'máy in',
    'bản đồ',
    'bỉ sa xí',
    'tơ pịa kẻ',
    'lịch',
    'á tính',
    'mỹ thuật',
    'khoa học',
    'lịch sử',
    'toán học',
    'văn học',
    'địa lý',
    'ngữ văn',
    'giáo dục thể chất',
    'mi xá lẹ',
    'bác sĩ',
    'y tá',
    'bệnh viện',
    'phòng khám',
    'hiệu thuốc',
    'thuốc',
    'nhi pay mạ',
    'hó da',
    'minh ma',
    'ma',
    'ma quá',
    'tơ xí í nhú',
    'đa í nhúng',
    'tơ xi khó',
    'tơ xi ma dú pị',
    'tơ xi ma hụng',
    'tơ xi ma chú ngụng',
    'tơ xi ma',
    'tờ xi nhí phá',
    'tơ xi phái',
    'tơ xí ché',
    'nhi túng',
    'tơ xi nhi khám',
    'huyết áp',
    'nhi cứ chợ',
    'chụp xquang',
    'tơ xe cừ mứ nhi',
    'tơ xi nhi túng',
    'bảo hiểm sức khoẻ',
    'tập thể dục',
    'tơ xi no hơ',
    'no hơ cho',
    'thể hình',
    'ha cung',
    'po tơ chi nẹ',
    'pha chẹ',
    'căng thẳng',
    'dợ lắm',
    'pu tin',
    'tơ xi nhu',
    'tơ xi cu pịa',
    'ba may tơ xin chẻ',
    'tơ xi ma',
    'pó mung tưa',
    'nỉ mủng',
    'tơ xi to',
    'tơ xi vớ',
    'hy vọng',
    'khao khát',
    'làm ơn',
    'bạn có thể',
    'bạn có thể làm ơn',
    'pó tư hò lẹ',
    'mờ cứ họ lẹ',
    'vò vỡ dạ',
    'vò vơ mủ',
    'vò dả nỉ mù',
    'mù chứ lạ',
    'di tứ lạ',
    'co phai mua',
    'tơ xi da múng gơ',
    'tơ xi vọng vơ',
    'tơ xi vớ',
    'po vòng tứ lạng',
    'tơ xe mung',
    'po mầy tứ lạ',
    'mươi xí',
    'pó mò'
  ];

  static void showLoadingDialog(BuildContext context, String text) {
    showDialog(
      context: context,
      barrierDismissible: false, // Prevent user from dismissing the dialog
      builder: (BuildContext context) {
        return Dialog(
          child: Padding(
            padding: const EdgeInsets.all(16.0),
            child: Row(
              mainAxisSize: MainAxisSize.min,
              children: [
                const CircularProgressIndicator(
                  color: Colors.orange,
                ),
                // Display a circular progress indicator
                const SizedBox(width: 16.0),
                Text(text),
                // Display a text message
              ],
            ),
          ),
        );
      },
    );
  }

  static void hideLoadingDialog(BuildContext context) {
    Navigator.of(context).pop(); // Close the dialog
  }

  static void showAlertDialog(
      BuildContext context, String title, String content) {
    showDialog(
      context: context,
      builder: (BuildContext context) {
        return AlertDialog(
          title: Text(title),
          content: Text(content),
          actions: <Widget>[
            TextButton(
              child: const Text("OK"),
              onPressed: () {
                Navigator.of(context).pop(); // Close the dialog
              },
            ),
          ],
        );
      },
    );
  }
}
