// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo-TmxP5XQSRiqG-Au0Sbvrgh1I_F1wSE',
    appId: '1:328618769365:web:50fcc89b881ae0f1805b5c',
    messagingSenderId: '328618769365',
    projectId: 'hello-e4ff8',
    authDomain: 'hello-e4ff8.firebaseapp.com',
    databaseURL: 'https://hello-e4ff8-default-rtdb.firebaseio.com',
    storageBucket: 'hello-e4ff8.firebasestorage.app',
    measurementId: 'G-BC8JMV92B6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIs_Q96HVbC2NslgsQo5fq09BHj0W4cUY',
    appId: '1:328618769365:android:ee573447f4334a01805b5c',
    messagingSenderId: '328618769365',
    projectId: 'hello-e4ff8',
    databaseURL: 'https://hello-e4ff8-default-rtdb.firebaseio.com',
    storageBucket: 'hello-e4ff8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZunSkS2MWkDPKL887AHTRn--g0VfUhnQ',
    appId: '1:328618769365:ios:5d1b1958c6899a04805b5c',
    messagingSenderId: '328618769365',
    projectId: 'hello-e4ff8',
    databaseURL: 'https://hello-e4ff8-default-rtdb.firebaseio.com',
    storageBucket: 'hello-e4ff8.firebasestorage.app',
    iosBundleId: 'com.tondz.tiengdantoc.dichTiengDanToc',
  );
}
